package com.chrinovicmm.listes

object Data {
    val listPersons = listOf(
        "Yves Kalume",
        "Achoura kangabu",
        "Eric Kabangala",
        "Eric Ampire",
        "Likeur Off",
        "Degaul Banza",
        "Schekinah Tshiokufila",
        "Christian Tshikwata",
        "Jules-Cesar Lusanga",
        "Chrinovic MUKEBA",
        "Plamedie Atia",
        "Sonia Chungu",
        "Schekinah Tshiokufila",
        "Christian Tshikwata",
        "Jules-Cesar Lusanga",
        "Chrinovic MUKEBA",
        "Plamedie Atia",
        "Sonia Chungu",
        "Schekinah Tshiokufila",
        "Christian Tshikwata",
        "Jules-Cesar Lusanga",
        "Chrinovic MUKEBA",
        "Plamedie Atia",
        "Sonia Chungu",
        "Schekinah Tshiokufila",
        "Christian Tshikwata",
        "Jules-Cesar Lusanga",
        "Chrinovic MUKEBA",
        "Plamedie Atia",
        "Sonia Chungu",
        "Schekinah Tshiokufila",
        "Christian Tshikwata",
        "Jules-Cesar Lusanga",
        "Chrinovic MUKEBA",
        "Plamedie Atia",
        "Sonia Chungu",
        "Schekinah Tshiokufila",
        "Christian Tshikwata",
        "Jules-Cesar Lusanga",
        "Chrinovic MUKEBA",
        "Plamedie Atia",
        "Sonia Chungu"
    )
}